import one from '../../assets/new/1.png'
import two from '../../assets/new/2.png'
import three from '../../assets/new/3.png'
import four from '../../assets/new/4.png'
import five from '../../assets/new/5.png'
import six from '../../assets/new/6.png'
import seven from '../../assets/new/7.png'
import eight from '../../assets/new/8.png'
import nine from '../../assets/new/9.png'

 
export default[
  {
    "img": one,
    "title": "Shoes 1",
    "desc": "Space for a small product description",
    "price": 23.5,
    "id": 1,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 4.5
  },
  {
    "img": two,
    "title": "Shoes 2",
    "desc": "Space for a small product description",
    "price": 33.9,
    "id": 2,
    "img1": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/sweet-pepper-colorful-sweet-bell-peppers-natural-royalty-free-image-1611355757.",
    "img2": "https://snaped.fns.usda.gov/sites/default/files/seasonal-produce/2018-05/bell%20peppers.jpg",
    "img3": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDsjHEvAMm98dV3G4iVwyBoQMPHRErjg2EIqmWkxQVfnR5EC0aviPePwru-LNVECzlc5Q&usqp=CAU",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 2.5
  },
  {
    "img": three,
    "title": "Shoes 3",
    "desc": "Space for a small product description",
    "price": 18.6,
    "id": 3,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 3.5
  },
  {
    "img": four,
    "title": "Shoes 4",
    "desc": "Space for a small product description",
    "price": 21.49,
    "id": 4,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 5
  },
  {
    "img": five,
    "title": "Shoes 5",
    "desc": "Space for a small product description",
    "price": 66.79,
    "id": 5,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 1
  },
  {
    "img": six,
    "title": "Shoes 6",
    "desc": "Space for a small product description",
    "price": 54.09,
    "id": 6,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 4
  },
  {
    "img": seven,
    "title": "Shoes 7",
    "desc": "Space for a small product description",
    "price": 83.48,
    "id": 7,
    "img1": "https://s.hdnux.com/photos/04/46/02/1204392/3/1200x0.jpg",
    "img2": "https://ichef.bbci.co.uk/news/976/cpsprodpb/9E86/production/_109228504_apples1.jpg",
    "img3": "https://www.higashine-cherry.jp/fruits-kingdom-higashine/wp-content/uploads/2019/11/apple.jpg",
    "img4": "https://4kwallpapers.com/images/wallpapers/red-apples-dew-drops-water-drops-pair-fruits-healthy-3840x2160-4921.jpg",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 3
  },
  {
    "img": eight,
    "title": "Shoes 8",
    "desc": "Space for a small product description",
    "price": 40.48,
    "id": 8,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 4
  },
  {
    "img": nine,
    "title": "Shoes 9",
    "desc": "Space for a small product description",
    "price": 71.49,
    "id": 9,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 4
  },
  {
    "img": nine,
    "title": "Shoes 10",
    "desc": "Space for a small product description",
    "price": 61.99,
    "id": 10,
    "img2": "",
    "img3": "",
    "page": "Carrots from Tomissy Farm are one of the best on the market. Tomisso and his family are giving a full love to his Bio products. Tomisso’s carrots are growing on the fields naturally.",
    "sku": "76645",
    "category": "Vegetables",
    "stock": "In Stock",
    "freshness": "1 Days Old",
    "delivery": "2 Days",
    "farm": "Grocery Tarm Fields",
    "area": "Czech republic",
    "discount": 48.56,
    "rating": 2
  }
]
